# Generated by Django 4.1.6 on 2023-09-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='main_user',
            new_name='user',
        ),
    ]
