# Generated by Django 4.1.6 on 2023-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userinfo_fb_link_alter_userinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fullname',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
